apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::486387019881:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-xCRPVS7v8JZu
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::486387019881:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-05T15:33:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1668"
  uid: cb331e80-49b6-4256-8b0a-1d687b3c0251
